### ISSUE TITLE
LICENSE Issue

### ISSUE THREAD

**Issue by ercanersoy** [emartisoft/GEMGUILib#1]
Hello, I'm interested GEMGUILib Project.

License of this software is GPL v2, but this license doesn't suitable for other licenses.

I would like change license of this software to a permissive license like MIT.

Thanks and best regards.

**Comment by emartisoft** [comment]
Ercan merhaba, lisans konusunda haklı olabilirsin ayrıntılı bilgim yok. Diğer lisanslar ile nasıl uyumsuz biraz açar mısın?

**Comment by ercanersoy** [comment]
Konuyu birçok kişinin okuyup anlayabilmesi için İngilizce olarak yazmıştım.

GPLv2 lisanslı bir kütüphaneyi GPLv2 olmayan bir program kullandığında sadece dinamik olarak bağlanması gerekiyor. Bu kütüphaneyi, bir GPLv2 olmayan bir programın içine yerleştirmek, bir başka deyişle statik bağlamak GPLv2'nin şartlarına ters düşmektedir.

Kütüphanenin kullanışlı olabilmesi için MIT Lisansı, LGPLv3 gibi lisanslarla lisanslanması gerekir. Günümüzde birçok açık kaynak yazılım, bazı üstünlüklerinden dolayı MIT Lisansı kullanmaktadır. Bence, kütüphanenin sonraki yapılarında MIT Lisansı kullanılırsa daha iyi olacağının düşünüyorum.

Teşekkür ederim.

**Comment by emartisoft** [comment]
Yazdıklarından aslında ben de kütüphaneyi dinamik olarak kullanılması yönünde derledim. Statik bir bağlantıda dediğin gibi MIT yada GPLv3 lisansı olarak değiştirelim. Asıl ben teşekkür ederim Ercan.

**Comment by ercanersoy** [comment]
GPLv3 yerine LGPLv3 demek istemiştim.

LGPLv3 lisansı yerine MIT Lisansı kullanılırsa daha iyi olacağını düşünüyorum. Çünkü, LGPLv3 lisansı çok uzun bir metindir ve daha az serbestlik sunar. MIT Lisansı, günümünüz açık kaynak dünyasında daha çok kullanılmaktadır.
