### ISSUE TITLE
about / exit in the middle of the screen

### ISSUE THREAD

**Issue by farvardin** [emartisoft/GEMGUILib#2]
When you have 2 screens, the "about" and "exit" splash screen are displayed in the middle of the 2 screens, making it difficultly readable because the screens are split. (it's not noticable on my screenshot of course)

![image](https://user-images.githubusercontent.com/477243/100143434-9f25ee00-2e95-11eb-8b3b-2f61ad40c875.png)

**Comment by emartisoft** [comment]
According to me, very cool screenshot! :)
It is fixed.
Thanks.

**Comment by farvardin** [comment]
thank you, it's good now!

If I could add more nickpicking, I'd say the last concern now is when I start the program on a double screen, it just start as well in the middle of the 2 screens. I don't really know how other piece of software are designed, some seems to open in the "almost" top left corner (of both screens, for example scite), some in the middle of the current screen (can be the one on the left or on the right, for example xedit). But none ever start at the middle of the two screens.

**Comment by emartisoft** [comment]
Ok. Please, open main.cpp and insert line.
Reference: https://qpcr4vir.github.io/nana-doxy/html/d9/dd8/classnana_1_1widget.html#a4e9fd1f4f527cf179a1424cd54950c49

```
int main()
{
	//window
	GEMForm af;
	af.size(nana::size(640,480));
	af.move(20,20); // INSERT LINE
	af.setTitle("GEM Skin Demo - Nana C++ GUI Project");
....
```

**Comment by farvardin** [comment]
great, thank you
